BARK_ARCHIVE: ''
BARK_GROUP: ''
BARK_ICON: ''
BARK_LEVEL: ''
BARK_PUSH: ''
BARK_SOUND: ''
BARK_URL: ''
CONSOLE: true
DD_BOT_SECRET: ''
DD_BOT_TOKEN: ''
DEER_KEY: ''
DEER_URL: ''
FSKEY: ''
GOBOT_QQ: ''
GOBOT_TOKEN: ''
GOBOT_URL: ''
GOTIFY_PRIORITY: 0
GOTIFY_TOKEN: ''
GOTIFY_URL: ''
HITOKOTO: false
IGOT_PUSH_KEY: ''
PUSH_KEY: ''
PUSH_PLUS_TOKEN: ''
PUSH_PLUS_USER: ''
QYWX_AM: ''
QYWX_KEY: 7d127e31-bea6-4894-89d4-143c4b8473b1
SMTP_EMAIL: ''
SMTP_EMAIL_TO: ''
SMTP_NAME: ''
SMTP_NAME_TO: ''
SMTP_PASSWORD: ''
SMTP_SERVER: ''
SMTP_SSL: 'true'
TG_API_HOST: ''
TG_BOT_TOKEN: ''
TG_PROXY_AUTH: ''
TG_PROXY_HOST: ''
TG_PROXY_PORT: ''
TG_USER_ID: ''
WXPUSHER_APP_TOKEN: ''
WXPUSHER_TOPIC_IDS: ''
WXPUSHER_UIDS: ''
