tasks:
- task: cloud189_auto_save
  name: 吞噬星空
  cron: 0 19 * * 3,4
  params:
    shareUrl: https://cloud.189.cn/t/nUfyIvuEZR7v
    targetDir: '623841196594583388'
    sourceDir: '923661157419801954'
    startMagic:
    - type: '{E}'
      symbol: '>'
      value: 175
    pattern: $TV_PRO
    isShareUrlValid: true
    replace: ''
  enabled: true
  next_run: '2025-06-25T19:00:00'
  last_execution:
    success: true
    message: 任务自动执行完成
    execution_time: '2025-06-20T17:37:40.826609'
    is_manual: false
- task: quark_auto_save
  name: 仙逆
  cron: 0 19-23 * * 1
  params:
    shareUrl: https://pan.quark.cn/s/9a602fb88089#/list/share/3ef42c29fbb64385a179d6ecae4566ff-千你
    targetDir: /仙逆
    startMagic:
    - type: '{E}'
      symbol: '>'
      value: 90
    pattern: $TV_PRO
    isShareUrlValid: true
    replace: ''
  enabled: true
  next_run: '2025-06-23T19:00:00'
  last_execution:
    success: true
    message: 任务自动执行完成
    execution_time: '2025-06-20T17:37:41.849609'
    is_manual: false
magic_regex:
  $TV:
    pattern: .*?([Ss]\d{1,2})?(?:[第EePpXx\.\-\_\( ]{1,2}|^)(\d{1,3})(?!\d).*?\.(mp4|mkv)
    replace: \1E\2.\3
  $BLACK_WORD:
    pattern: ^(?!.*纯享)(?!.*加更)(?!.*超前企划)(?!.*训练室)(?!.*蒸蒸日上).*
    replace: ''
  $SHOW_PRO:
    pattern: ^(?!.*纯享)(?!.*加更)(?!.*抢先)(?!.*预告).*?第\d+期.*
    replace: '{II}.{TASKNAME}.{DATE}.第{E}期{PART}.{EXT}'
  $TV_PRO:
    pattern: ''
    replace: '{TASKNAME}.{SXX}E{E}.{EXT}'
