magic_regex:
  $TV:
    pattern: .*?([Ss]\d{1,2})?(?:[第EePpXx\.\-\_\( ]{1,2}|^)(\d{1,3})(?!\d).*?\.(mp4|mkv)
    replace: \1E\2.\3
  $BLACK_WORD:
    pattern: ^(?!.*纯享)(?!.*加更)(?!.*超前企划)(?!.*训练室)(?!.*蒸蒸日上).*
    replace: ''
  $SHOW_PRO:
    pattern: ^(?!.*纯享)(?!.*加更)(?!.*抢先)(?!.*预告).*?第\d+期.*
    replace: '{II}.{TASKNAME}.{DATE}.第{E}期{PART}.{EXT}'
  $TV_PRO:
    pattern: ''
    replace: '{TASKNAME}.{SXX}E{E}.{EXT}'
tasks:
- task: cloud189_auto_save
  name: 七根心简
  cron: '* 19-23 * * *'
  params:
    shareUrl: https://cloud.189.cn/t/UBvyUziiA3qa
    targetDir: '825081198641713764'
    sourceDir: '123341197928769983'
    startMagic: []
    pattern: ''
    replace: ''
  enabled: true
  next_run: '2025-06-20T19:00:00'
  last_execution:
    success: true
    message: 任务自动执行完成
    execution_time: '2025-06-20T15:47:40.306305'
    is_manual: false
  is_running: false
- task: cloud189_auto_save
  name: 临江仙
  cron: 0 19-23 * * *
  params:
    shareUrl: https://cloud.189.cn/t/UVnIbquI7bQ3
    targetDir: '-11'
    startMagic: []
    pattern: $TV_PRO
    isShareUrlValid: false
    replace: $TV_PRO
  enabled: false
  next_run: '2025-06-20T19:00:00'
  last_execution:
    success: true
    message: 任务自动执行完成
    execution_time: '2025-06-20T15:47:42.841876'
    is_manual: false
