tasks:
- task: cloud189_auto_save
  name: 吞噬星空
  cron: 0 19 * * 3,4
  params:
    shareUrl: https://cloud.189.cn/t/nUfyIvuEZR7v
    targetDir: '623841196594583388'
    sourceDir: '923661157419801954'
    startMagic:
    - type: '{E}'
      symbol: '>'
      value: 175
    pattern: $TV_PRO
    isShareUrlValid: true
    replace: '{TASKNAME}.S01E{E}.{EXT}'
  enabled: true
  next_run: '2025-06-25T19:00:00'
  last_execution:
    success: true
    message: 任务自动执行完成
    execution_time: '2025-06-21T21:19:25.229662'
    is_manual: false
  is_running: false
magic_regex:
  $TV:
    pattern: .*?([Ss]\d{1,2})?(?:[第EePpXx\.\-\_\( ]{1,2}|^)(\d{1,3})(?!\d).*?\.(mp4|mkv)
    replace: \1E\2.\3
  $BLACK_WORD:
    pattern: ^(?!.*纯享)(?!.*加更)(?!.*超前企划)(?!.*训练室)(?!.*蒸蒸日上).*
    replace: ''
  $SHOW_PRO:
    pattern: ^(?!.*纯享)(?!.*加更)(?!.*抢先)(?!.*预告).*?第\d+期.*
    replace: '{II}.{TASKNAME}.{DATE}.第{E}期{PART}.{EXT}'
  $TV_PRO:
    pattern: ''
    replace: '{TASKNAME}.{SXX}E{E}.{EXT}'
