alist_api_key: ''
alist_url: ''
emby_api_key: 28084b2ccda14a949feb2e39c8158665
emby_url: http://192.168.2.197:8096
quarkCookie: b-user-id=d414d7bc-146f-3885-3e9f-b472b03f5fbb;_UP_A4A_11_=wb96714368114d149eebc7d5f9ecfffb;cna=1rILIGy78TwCAd+nymrRwGrP;__sdid=AAS2GUFpR5c2A0Ox/he7+YEfm0TmlF2WG+YwDyzTlwzDp+5txCJmmb2B0dQn23pFxec=;xlly_s=1;_UP_D_=pc;isg=BLCw5C1arIXn_X51wrl2DBSLgX4C-ZRDnMU1G6oAy4vpZVIPUg3F09JWuW0FVEwb;_UP_F7E_8D_=84%2BjZ7SHtvZVhgEp2%2FBQlfjdGzlxqy3HGUOU%2BWEa1%2FCQ9pt%2Flxcgspx%2F7jdZxm88%2BDZR%2F3OCavVVlSrlA%2FHE35guhUiWeFXSFrpiz7iQup7LB%2BL83Dn0lIDh36hnRcflW%2FQJYV4NNTs66CrfFO0aJKNtsvO2m7ODLbPeoOdhK0F%2B4CVxwd%2BA5kyclW53hcuTOm0qJXeruCvE8Rq5JJS3OWWGykxEkhcXkbuiW4cJiR%2BJsCDavVJcUYInCxl1g1C0s1YxLzJs52lWdoIk19nvWfytP81cJKxfv1GfwBTrR0bS%2FBGt91fGhZMwyZvOKbU%2F8ZkbgrGvmwxqzivluzXqQHrmHUwax9fVlczEGdRq2nJkSi56LgyDrXpsyYdGYA0F4Cj%2Fntr80vkUTca5E0LqLcBEt4UN6jDY;_UP_30C_6A_=st9c9620116vxicpsbch2qqdjzpo3cl3;_UP_TS_=sg141b910e9233b62f09165bd8155ad7bba;_UP_E37_B7_=sg141b910e9233b62f09165bd8155ad7bba;_UP_TG_=st9c9620116vxicpsbch2qqdjzpo3cl3;_UP_335_2B_=1;__pus=aae34232891820efb5863578d63dd2c8AASKKD09KdH+1Ju5YdHCUybwkeoZG56cB8E26yn2jdTS6qfLc9pG7KSbXrj4XOkhcIzycpYps9AVVCsloWBlNUEE;__kp=750bf0c0-3b73-11f0-9dbe-9392fbcf4635;__kps=AAT2TYW9X92W+l2bQL4EoM8L;__ktd=PLctoxaNr6ojanuwHxKzkA==;__uid=AAT2TYW9X92W+l2bQL4EoM8L;tfstk=gVoshRxAH1f6jNqAhPvFASi1iGZjfp-yCtwxExINHlEODjM0TR7wSrRjRjhU6c8g_XNjUxj4_Ar9hjG-1rljnd2YMjhbgV8e4ADgmodPc3-rIjucyWh_koIpH-wYMpzTo9qK7odyaH-Mfd4bDj7vunLIpW2bHsFtM9pQH-ZAXrIOJ6F39oeYBNCKp-wlBSFtMvpQnWFYDohYvpwmBA-QLKPsCd78BGWcYIM_OiIxAJd09A6l0JigCuF-BfIADUe_57HTOQRK_ZaKnricniaqB4c0efC9GSmIpc3-wB7a64wjUqGJ3N2UlcqQMcKlFWnshDai81QTFlN_ycU1ULDgk2iQbcdcrvkQ6zZE8eAaulGsr749-Bcjd5lxfyC6TSurLcUIwBSIirgxbkn993sPFgP7UIbfdzjYd7JBdZb037fxQyIv_v4TKJ5ydp1_vPe3d7JBdZb0WJ2eUp9C1kC..;__puus=235294fe3ed011b48f2e57ee6579e0b4AATanetMEu37fAt66Oxdm85ipk02cgxfcmhMwmKT2dlGp4fTasVm646SUW2rBf/n1JgE9dByjosHMD3gvR47wrkjXxGRicyvj1T3D5j0/vYR6jKrJpCFjGhOKXOpeS8S8mYTCpYsBD3Q0bCLB0Yvc2dxLrVBIM+44lu48Xe10Y4rq7WQ3UXZ0YKvokcyTUGVOPZTi+YZm4CLVhJhaDRrq48u
tianyiAccount: '18607147683'
tianyiPassword: wzq520hxh
cloud189_session:
  access_token: 18fe5049c62a447db8e1150ed5c1ea10
  session_key: 49ecc063-69f6-4f67-a482-b8e0d4ea71da
  expires_in: 1750911377
use_proxy: false
proxy_host: 127.0.0.1
proxy_port: '7897'
proxy_username: null
proxy_password: null
tg_resource:
  telegram:
    baseUrl: https://t.me/s
    channels:
    - id: yunpanqk
      name: 网盘资源收藏(夸克)
    - id: tyypzhpd
      name: 天翼云盘综合频道
  cloudPatterns:
    aliyun: https?://www\.aliyundrive\.com/s/[a-zA-Z0-9]+
    tianyiyun: https?://cloud\.189\.cn/t/[a-zA-Z0-9]+
    quark: https?://pan\.quark\.cn/s/[a-zA-Z0-9]+
    baidu: https?://pan\.baidu\.com/s/[a-zA-Z0-9_-]+
