app:
  title: "MediaHelper API"
  description: "Media Helper Backend Service"
  version: "1.0.0"
  API_V1_STR: "/api/v1"
  debug: false

server:
  host: "0.0.0.0"
  port: 5555

database:
  async_url: "sqlite+aiosqlite:///./prod.db"
  url: "sqlite:///./prod.db"

logging:
  level: "INFO"

security:
  secret_key: "j9x#K2P$mN8vL4qR7tY3wZ6hC9nB5gF1sA4dE8kM2pQ"  # 使用随机生成的强密钥
  algorithm: "HS256"
  access_token_expire_minutes: 30 